In [7]:
#4. 
#a
import numpy as np
arr=np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [8]:
#b
import numpy as np
arr=np.ones(10)
print(arr)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [9]:
#c
import numpy as np
arr=np.full(10,5)
print(arr)

[5 5 5 5 5 5 5 5 5 5]


In [11]:
#e
import numpy as np
arr=np.arange(10,51)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [12]:
#f
import numpy as np
arr=np.arange(10,51,2)
print(arr)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [14]:
#g
import numpy as np
arr=np.arange(0,9)
arr=arr.reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [16]:
#h
import numpy as np
a=np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [38]:
#i
import numpy as np
a=np.random.rand()
print(a)

0.3830781773289885


In [41]:
#j
import numpy as np
a=np.random.randn(25)
print(a)

[ 1.22750378e+00 -1.04425283e-01 -8.42631318e-01 -1.74234914e+00
 -5.49522080e-01  5.24062364e-01  1.00795760e-01 -1.56735472e+00
 -1.96296749e+00  5.83902175e-01  2.63110631e-01  7.77201645e-01
 -1.30664298e+00  3.03203926e+00 -1.81816249e+00 -4.19639329e-01
 -6.09777700e-01  2.47192122e-01  7.44146776e-01  2.89481692e-01
  4.02590789e-02 -5.56237495e-01 -5.24281591e-01 -3.36550385e-01
  2.39043168e-03]


In [48]:
#k
import numpy as np
a=np.arange(0,1,0.01)
a=a.reshape(10,10)
print(a)

[[0.   0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09]
 [0.1  0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19]
 [0.2  0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29]
 [0.3  0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39]
 [0.4  0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49]
 [0.5  0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59]
 [0.6  0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69]
 [0.7  0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79]
 [0.8  0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89]
 [0.9  0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99]]


In [96]:
#i
# это наша стартовая матрица
mat = np.arange(1,26).reshape(5,5)
print(mat[2:,1:])
print('-------------')
#m
print(mat[3,4])
print('-------------')
#n
mat=np.arange(1,26).reshape(5,5)
mat2=mat.reshape(5,-1)
print(mat2[0:3,1:2])
print('-------------')
#o
print(mat[4:,0:])
print('-------------')
#p
print(mat[3:,0:])
print('-------------')
#q
a=np.sum(mat)
print(a)
print('-------------')
#r
a=np.std(mat)
print(a)
print('-------------')
#s
print(sum(mat))
print('-------------')

[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]
-------------
20
-------------
[[ 2]
 [ 7]
 [12]]
-------------
[[21 22 23 24 25]]
-------------
[[16 17 18 19 20]
 [21 22 23 24 25]]
-------------
325
-------------
7.211102550927978
-------------
[55 60 65 70 75]
-------------
